[[hooks]]
stage = "build"
command = "bash"
command_arguments = ["-c", """
  WASM_BINDGEN_THREADS_STACK_SIZE=16777216 wasm-pack build --no-pack \
                  --$(echo $TRUNK_PROFILE | sed s/debug/dev/) \
                  --no-typescript \
                  --target web \
                  --out-dir $TRUNK_STAGING_DIR \
                  worker && \
  if [ "$TRUNK_PROFILE" == "release" ]; then \
    echo "Running wasm-opt..."; \
    wasm-opt --enable-threads \
             --enable-bulk-memory \
             -O4 $TRUNK_STAGING_DIR/worker_bg.wasm \
             -o $TRUNK_STAGING_DIR/worker_bg.wasm; \
  fi \
  """]

[[hooks]]
stage = "build"
command = "bash"
command_arguments = ["-c", """
  npm install && \
  node_modules/.bin/rollup codemirror_interface.ts -f es \
      -o $TRUNK_STAGING_DIR/codemirror.js \
      -p @rollup/plugin-node-resolve \
      -p @rollup/plugin-typescript
  """]

