[build]
public_url = "."
minify = "on_release"

[[hooks]]
stage = "build"
command = "bash"
command_arguments = ["-c", """
  cd codemirror && \
  npm install && \
  node_modules/.bin/rollup codemirror_interface.ts -f es \
      -o $TRUNK_STAGING_DIR/codemirror.js \
      -p @rollup/plugin-node-resolve \
      -p @rollup/plugin-typescript \
      $([ "$TRUNK_PROFILE" = "release" ] && echo -p @rollup/plugin-terser)
  """]

