//! End-to-end coverage for the compiled Web Worker.
//!
//! `wasm-bindgen-test-runner` serves static files from the package directory, which is why this
//! test belongs to the root `wasm-ide` package: the worker generated by `trunk build` is then
//! available under `/dist`. The runner normally wraps nested workers in a blob URL to capture
//! their logs, but that would prevent the worker's relative `./compilers/cpp.tar` request from
//! resolving. `createWorker` therefore uses an otherwise empty same-origin iframe's untouched
//! `Worker` constructor, preserving the same HTTP-relative behavior used in production.

use common::{
    ExecConfig, File, Language, WorkerExecRequest, WorkerExecResponse, WorkerExecStatus,
    WorkerLSRequest, WorkerLSResponse, WorkerRequest, WorkerResponse,
};
use futures::StreamExt;
use futures::channel::mpsc::{UnboundedReceiver, unbounded};
use serde::de::DeserializeOwned;
use wasm_bindgen::JsCast;
use wasm_bindgen::prelude::*;
use wasm_bindgen_test::*;
use web_sys::{MessageEvent, Worker};

wasm_bindgen_test_configure!(run_in_browser);

const CPP_SOURCE: &str = r#"#include <iostream>

int main() {
    int value;
    std::cin >> value;
    std::cout << value + 1 << '\n';
}
"#;

#[wasm_bindgen(inline_js = r#"
const workerFrames = new WeakMap();

export function createWorker(url) {
    const frame = document.createElement("iframe");
    frame.style.display = "none";
    document.body.appendChild(frame);

    const workerUrl = new URL(url, document.baseURI).href;
    const worker = new frame.contentWindow.Worker(workerUrl, { type: "module" });
    workerFrames.set(worker, frame);
    return worker;
}

export function disposeWorker(worker) {
    worker.terminate();
    const frame = workerFrames.get(worker);
    if (frame !== undefined) {
        frame.remove();
        workerFrames.delete(worker);
    }
}
"#)]
extern "C" {
    #[wasm_bindgen(js_name = createWorker)]
    fn create_worker(url: &str) -> Worker;

    #[wasm_bindgen(js_name = disposeWorker)]
    fn dispose_worker(worker: &Worker);
}

enum WorkerEvent {
    Message(JsValue),
    Error(String),
}

struct TestWorker {
    worker: Worker,
    events: UnboundedReceiver<WorkerEvent>,
    _on_message: Closure<dyn FnMut(MessageEvent)>,
    _on_error: Closure<dyn FnMut(JsValue)>,
}

impl TestWorker {
    fn start() -> Self {
        let (sender, events) = unbounded();
        let worker = create_worker("/dist/worker_loader.js");

        let message_sender = sender.clone();
        let on_message = Closure::<dyn FnMut(_)>::new(move |event: MessageEvent| {
            let _ = message_sender.unbounded_send(WorkerEvent::Message(event.data()));
        });
        worker.set_onmessage(Some(on_message.as_ref().unchecked_ref()));

        let error_sender = sender;
        let on_error = Closure::<dyn FnMut(_)>::new(move |event: JsValue| {
            let message = js_sys::Reflect::get(&event, &"message".into())
                .ok()
                .and_then(|message| message.as_string())
                .unwrap_or_else(|| "unknown worker error".to_owned());
            let _ = error_sender.unbounded_send(WorkerEvent::Error(message));
        });
        worker.set_onerror(Some(on_error.as_ref().unchecked_ref()));

        Self {
            worker,
            events,
            _on_message: on_message,
            _on_error: on_error,
        }
    }

    fn send(&self, request: impl Into<WorkerRequest>) {
        let request =
            serde_wasm_bindgen::to_value(&request.into()).expect("serialize worker request");
        self.worker
            .post_message(&request)
            .expect("post worker request");
    }

    async fn receive<T: DeserializeOwned>(&mut self) -> T {
        let message = match self.events.next().await.expect("worker event stream ended") {
            WorkerEvent::Message(message) => message,
            WorkerEvent::Error(error) => panic!("worker failed: {error}"),
        };
        serde_wasm_bindgen::from_value(message).expect("deserialize worker message")
    }

    async fn expect_language(&mut self, expected: &str) {
        let languages: Vec<Language> = self.receive().await;
        assert!(
            languages.iter().any(|language| language.name == expected),
            "worker did not advertise {expected}"
        );
    }
}

impl Drop for TestWorker {
    fn drop(&mut self) {
        dispose_worker(&self.worker);
    }
}

#[wasm_bindgen_test]
async fn compile_and_run() {
    let mut worker = TestWorker::start();
    worker.expect_language("C++").await;
    worker.send(WorkerExecRequest::Run {
        files: vec![File {
            name: "main.cpp".to_owned(),
            content: CPP_SOURCE.as_bytes().to_vec(),
        }],
        primary_file: "main.cpp".to_owned(),
        language: "C++".to_owned(),
        input: Some(b"41\n".to_vec()),
        config: ExecConfig::default(),
    });

    let expected_statuses = [
        WorkerExecStatus::FetchingCompiler,
        WorkerExecStatus::Compiling,
        WorkerExecStatus::Running,
    ];
    let mut status_index = 0;
    let mut saw_fetch_progress = false;
    let mut saw_fetch_done = false;
    let mut succeeded = false;
    let mut stdout = Vec::new();
    let mut stderr = Vec::new();
    let mut compiler_output = Vec::new();

    while !(succeeded
        && saw_fetch_done
        && status_index == expected_statuses.len()
        && stdout.len() >= b"42\n".len())
    {
        let response: WorkerResponse = worker.receive().await;
        match response {
            WorkerResponse::FetchingCompiler(name, _) => {
                assert_eq!(name, "cpp");
                saw_fetch_progress = true;
            }
            WorkerResponse::CompilerFetchDone(name) => {
                assert_eq!(name, "cpp");
                saw_fetch_done = true;
            }
            WorkerResponse::Execution(WorkerExecResponse::Status(status)) => {
                let expected = expected_statuses
                    .get(status_index)
                    .expect("received an unexpected extra execution status");
                assert_eq!(
                    std::mem::discriminant(expected),
                    std::mem::discriminant(&status),
                    "execution statuses arrived out of order"
                );
                status_index += 1;
            }
            WorkerResponse::Execution(WorkerExecResponse::CompilationMessageChunk(chunk)) => {
                compiler_output.extend(chunk);
            }
            WorkerResponse::Execution(WorkerExecResponse::StdoutChunk(chunk)) => {
                stdout.extend(chunk);
            }
            WorkerResponse::Execution(WorkerExecResponse::StderrChunk(chunk)) => {
                stderr.extend(chunk);
            }
            WorkerResponse::Execution(WorkerExecResponse::Success) => succeeded = true,
            WorkerResponse::Execution(WorkerExecResponse::Error(error)) => {
                panic!(
                    "compile-and-run failed: {error}\ncompiler output: {}\nstderr: {}",
                    String::from_utf8_lossy(&compiler_output),
                    String::from_utf8_lossy(&stderr)
                );
            }
            WorkerResponse::LS(_) => panic!("unexpected language-server response"),
        }
    }

    assert!(
        saw_fetch_progress,
        "compiler download did not report progress"
    );
    assert_eq!(stdout, b"42\n", "unexpected program output");
    assert!(
        stderr.is_empty(),
        "unexpected stderr: {}",
        String::from_utf8_lossy(&stderr)
    );
}

async fn receive_lsp_response(worker: &mut TestWorker, expected_id: u64) -> serde_json::Value {
    loop {
        match worker.receive::<WorkerResponse>().await {
            WorkerResponse::LS(WorkerLSResponse::Message(message)) => {
                let message: serde_json::Value =
                    serde_json::from_str(&message).expect("parse language-server response");
                if message.get("id").and_then(serde_json::Value::as_u64) == Some(expected_id) {
                    return message;
                }
            }
            WorkerResponse::LS(WorkerLSResponse::Error(error)) => {
                panic!("language server failed: {error}")
            }
            WorkerResponse::LS(WorkerLSResponse::Stopped) => {
                panic!("language server stopped before responding to request {expected_id}")
            }
            WorkerResponse::LS(_) | WorkerResponse::FetchingCompiler(_, _) => {}
            WorkerResponse::CompilerFetchDone(_) => {}
            WorkerResponse::Execution(_) => panic!("unexpected execution response"),
        }
    }
}

#[wasm_bindgen_test]
async fn lsp() {
    const CODE_DIR: &str = "worker-lsp-test";

    let opfs = common::opfs::root().await;
    if opfs.contains_dir(CODE_DIR).await {
        opfs.remove_entry(CODE_DIR, true).await;
    }
    let code_dir = opfs.open_dir(CODE_DIR, true).await;
    code_dir
        .open_file("main.cpp", true)
        .await
        .write(CPP_SOURCE.as_bytes())
        .await;

    let mut worker = TestWorker::start();
    worker.expect_language("C++").await;
    worker.send(WorkerLSRequest::Start {
        language: "C++".to_owned(),
        code_dir: CODE_DIR.to_owned(),
    });

    let mut saw_fetch_progress = false;
    let mut saw_fetch_done = false;
    loop {
        match worker.receive::<WorkerResponse>().await {
            WorkerResponse::FetchingCompiler(name, _) => {
                assert_eq!(name, "cpp");
                saw_fetch_progress = true;
            }
            WorkerResponse::CompilerFetchDone(name) => {
                assert_eq!(name, "cpp");
                saw_fetch_done = true;
            }
            WorkerResponse::LS(WorkerLSResponse::Started) => break,
            WorkerResponse::LS(WorkerLSResponse::FetchingCompiler) => {}
            WorkerResponse::LS(WorkerLSResponse::Error(error)) => {
                panic!("language server failed to start: {error}")
            }
            WorkerResponse::LS(response) => {
                panic!("unexpected language-server startup response: {response:?}")
            }
            WorkerResponse::Execution(_) => panic!("unexpected execution response"),
        }
    }
    assert!(
        saw_fetch_progress,
        "compiler download did not report progress"
    );
    assert!(saw_fetch_done, "compiler download did not finish");

    worker.send(WorkerLSRequest::Message(
        serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "initialize",
            "params": {
                "processId": null,
                "rootUri": "file:///workdir",
                "capabilities": {}
            }
        })
        .to_string(),
    ));
    let initialize = receive_lsp_response(&mut worker, 1).await;
    assert!(
        initialize.get("result").is_some(),
        "initialize returned no result: {initialize}"
    );

    worker.send(WorkerLSRequest::Message(
        serde_json::json!({
            "jsonrpc": "2.0",
            "method": "initialized",
            "params": {}
        })
        .to_string(),
    ));
    worker.send(WorkerLSRequest::Message(
        serde_json::json!({
            "jsonrpc": "2.0",
            "method": "textDocument/didOpen",
            "params": {
                "textDocument": {
                    "uri": "file:///workdir/main.cpp",
                    "languageId": "cpp",
                    "version": 1,
                    "text": CPP_SOURCE
                }
            }
        })
        .to_string(),
    ));
    worker.send(WorkerLSRequest::Message(
        serde_json::json!({
            "jsonrpc": "2.0",
            "id": 2,
            "method": "textDocument/documentSymbol",
            "params": {
                "textDocument": { "uri": "file:///workdir/main.cpp" }
            }
        })
        .to_string(),
    ));

    let symbols = receive_lsp_response(&mut worker, 2).await;
    let symbols = symbols
        .get("result")
        .and_then(serde_json::Value::as_array)
        .expect("documentSymbol result should be an array");
    assert!(
        symbols
            .iter()
            .any(|symbol| symbol.get("name").and_then(serde_json::Value::as_str) == Some("main")),
        "documentSymbol did not return main: {symbols:?}"
    );

    worker.send(WorkerLSRequest::Message(
        serde_json::json!({
            "jsonrpc": "2.0",
            "id": 3,
            "method": "shutdown",
            "params": null
        })
        .to_string(),
    ));
    let shutdown = receive_lsp_response(&mut worker, 3).await;
    assert_eq!(shutdown.get("result"), Some(&serde_json::Value::Null));
    worker.send(WorkerLSRequest::Message(
        serde_json::json!({
            "jsonrpc": "2.0",
            "method": "exit",
            "params": null
        })
        .to_string(),
    ));

    loop {
        match worker.receive::<WorkerResponse>().await {
            WorkerResponse::LS(WorkerLSResponse::Stopped) => break,
            WorkerResponse::LS(WorkerLSResponse::Message(_)) => {}
            WorkerResponse::LS(WorkerLSResponse::Error(error)) => {
                panic!("language server failed while stopping: {error}")
            }
            response => panic!("unexpected response while stopping language server: {response:?}"),
        }
    }

    opfs.remove_entry(CODE_DIR, true).await;
}
