[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
console_error_panic_hook = "0.1.7"
tracing = { version = "0.1.41", features = ["release_max_level_info"] }
tracing-subscriber = "0.3.20"
tracing-web = "0.1.3"
