[build]
target = "wasm32-unknown-unknown"

[target.'cfg(target_arch = "wasm32")']
rustflags = [
  "-C", "link-arg=--max-memory=4294967296",
  "-C", "link-args=-z stack-size=16777216",
]

[unstable]
build-std = ["std", "panic_abort"]
