name: Rust

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  clippy:
    name: Cargo Format & Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: cargo fmt
        run: cargo fmt --check

      - name: cargo clippy
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings

      - name: trunk build
        run: |
          mkdir compilers
          trunk build
